// @ts-ignore swisseph has incomplete typings
import swisseph from 'swisseph';
import { AspectHit, HouseCusp, NatalChartResult, PlanetPosition } from '../types/astrology';
const SIGNS_TR=['Koç','Boğa','İkizler','Yengeç','Aslan','Başak','Terazi','Akrep','Yay','Oğlak','Kova','Balık'];
const SIGNS_EN=['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'];
export const PLANET_IDS:Record<string,number>={Sun:0,Moon:1,Mercury:2,Venus:3,Mars:4,Jupiter:5,Saturn:6,Uranus:7,Neptune:8,Pluto:9,Chiron:15,NorthNode:11};
const PLANETS_TR:Record<string,string>={Sun:'Güneş',Moon:'Ay',Mercury:'Merkür',Venus:'Venüs',Mars:'Mars',Jupiter:'Jüpiter',Saturn:'Satürn',Uranus:'Uranüs',Neptune:'Neptün',Pluto:'Plüton',Chiron:'Kiron',NorthNode:'Kuzey Düğüm'};
export const ASPECT_DEFINITIONS=[{type:'Conjunction',nameTR:'Kavuşum',angle:0,orb:8},{type:'Sextile',nameTR:'Sekstil',angle:60,orb:6},{type:'Square',nameTR:'Kare',angle:90,orb:7},{type:'Trine',nameTR:'Trigon',angle:120,orb:7},{type:'Opposition',nameTR:'Karşıt',angle:180,orb:8}];
export function normalize360(n:number){return ((n%360)+360)%360;}
export function angularDistance(a:number,b:number){const d=Math.abs(normalize360(a)-normalize360(b));return d>180?360-d:d;}
export function lonToSign(lon:number){const n=normalize360(lon),i=Math.floor(n/30),deg=n%30,d=Math.floor(deg),m=Math.floor((deg-d)*60);return{sign:SIGNS_EN[i],signTR:SIGNS_TR[i],degree:deg,formatted:`${d}°${String(m).padStart(2,'0')}' ${SIGNS_TR[i]}`};}
export function toJulianDay(date:string,time:string,utcOffsetMinutes:number){const [y,mo,d]=date.split('-').map(Number),[h,mi]=time.split(':').map(Number);return swisseph.swe_julday(y,mo,d,(h*60+mi-utcOffsetMinutes)/60,swisseph.SE_GREG_CAL);}
function calcPlanet(jd:number,id:number,flags=swisseph.SEFLG_SPEED|swisseph.SEFLG_SWIEPH):Promise<{longitude:number;speed:number;flag:number}>{return new Promise((resolve,reject)=>{let done=false;const cb=(r:any)=>{if(done)return;if(!r||r.error){done=true;return reject(new Error(r?.error||'swe_calc_ut başarısız'));}done=true;resolve({longitude:normalize360(Number(r.longitude)),speed:Number(r.longitudeSpeed??r.speedInLong??0),flag:flags});};try{const r=swisseph.swe_calc_ut(jd,id,flags,cb);if(r&&typeof r==='object'&&'longitude'in r)cb(r);}catch(e){reject(e);}});}
async function calcPlanetWithFallback(jd:number,id:number){try{return await calcPlanet(jd,id);}catch{const flags=swisseph.SEFLG_SPEED|swisseph.SEFLG_MOSEPH;return {...await calcPlanet(jd,id,flags),fallback:true};}}
export async function getPlanetPositionsAtJulianDay(jd:number){const results=await Promise.all(Object.entries(PLANET_IDS).map(async([name,id])=>{try{const p=await calcPlanetWithFallback(jd,id);return{name,...p};}catch{return null;}}));return results.filter(Boolean) as Array<{name:string;longitude:number;speed:number;flag:number;fallback?:boolean}>;}
async function calcHouses(jd:number,lat:number,lon:number,hsys:string){return new Promise<{house:number[];ascendant:number;mc:number}>((resolve,reject)=>{let done=false;const cb=(r:any)=>{if(done)return;if(!r||r.error){done=true;return reject(new Error(r?.error||'swe_houses başarısız'));}done=true;resolve({house:r.house,ascendant:normalize360(r.ascendant),mc:normalize360(r.mc)});};try{const code=(hsys?.[0]?.toUpperCase()||'P');const r=swisseph.swe_houses(jd,lat,lon,code,cb);if(r&&typeof r==='object'&&('house'in r||'ascendant'in r))cb(r);}catch(e){reject(e);}});}
export function findHouse(lon:number,cusps:number[]){if(!cusps.length)return 1;for(let i=0;i<cusps.length;i++){const s=normalize360(cusps[i]),e=normalize360(cusps[(i+1)%cusps.length]);if(s<e?(lon>=s&&lon<e):(lon>=s||lon<e))return i+1;}return 1;}
export function computeAspects(planets:PlanetPosition[]):AspectHit[]{const out:AspectHit[]=[];for(let i=0;i<planets.length;i++)for(let j=i+1;j<planets.length;j++){const diff=angularDistance(planets[i].longitude,planets[j].longitude);for(const a of ASPECT_DEFINITIONS){const orb=Math.abs(diff-a.angle);if(orb<=a.orb){out.push({planet1:planets[i].planet,planet2:planets[j].planet,type:a.type,typeTR:a.nameTR,angle:a.angle,orb:Number(orb.toFixed(3))});break;}}}return out;}
export async function calculateNatalChart(date:string,time:string,city:string,lat:number,lon:number,utcOffsetMinutes:number,houseSystem='Placidus',timezone='UTC'):Promise<NatalChartResult>{const jd=toJulianDay(date,time,utcOffsetMinutes);const raw=await getPlanetPositionsAtJulianDay(jd);const fallbackUsed=raw.some(p=>p.fallback);let asc=0,mc=0,cusps:number[]=[];const warnings:string[]=[];try{const h=await calcHouses(jd,lat,lon,houseSystem);asc=h.ascendant;mc=h.mc;cusps=h.house;}catch(e){warnings.push('House calculation fallback kullanıldı');asc=raw.find(p=>p.name==='Sun')?.longitude||0;cusps=Array.from({length:12},(_,i)=>normalize360(asc+i*30));mc=normalize360(asc+270);}
const planets:PlanetPosition[]=raw.map(p=>{const s=lonToSign(p.longitude);return{planet:p.name,planetTR:PLANETS_TR[p.name]||p.name,longitude:p.longitude,sign:s.sign,signTR:s.signTR,degree:s.degree,degreeFormatted:s.formatted,isRetrograde:p.speed<0,house:findHouse(p.longitude,cusps),speed:p.speed};});
const houses:HouseCusp[]=cusps.map((c,i)=>{const s=lonToSign(c);return{house:i+1,longitude:c,sign:s.sign,signTR:s.signTR,degree:s.degree,degreeFormatted:s.formatted};});const ad=lonToSign(asc),sun=planets.find(p=>p.planet==='Sun'),moon=planets.find(p=>p.planet==='Moon');
return{birthData:{date,time,city},location:{lat,lon,timezone,utcOffsetMinutes},julianDay:Number(jd.toFixed(8)),houseSystem,calculatedAt:new Date().toISOString(),engine:fallbackUsed?'moshier-fallback':'swisseph',calculationMeta:{engine:fallbackUsed?'moshier-fallback':'swisseph',fallbackUsed,warnings},planets,houses,angles:{ASC:asc,MC:mc,IC:normalize360(mc+180),DSC:normalize360(asc+180),ascSign:ad.sign,ascSignTR:ad.signTR,ascFormatted:ad.formatted},aspects:computeAspects(planets),sunSign:sun?.sign||'',sunSignTR:sun?.signTR||'',moonSign:moon?.sign||'',moonSignTR:moon?.signTR||'',ascendant:ad.sign,ascendantTR:ad.signTR};}
