import axios from 'axios';
import { env } from '../config/env.config';
import { getUserById, upsertSubscription } from './user.service';

export interface PremiumStatus { isPremium:boolean; expiresAt:string|null; productId:string|null; willRenew:boolean; status:string; trialEndsAt:string|null; appUserId:string; }
function subFor(entitlement:any,subscriptions:any){if(!entitlement)return{isPremium:false,expiresAt:null,productId:null,willRenew:false,status:'inactive',trialEndsAt:null};const expires=entitlement.expires_date?new Date(entitlement.expires_date):null;const product=entitlement.product_identifier||null;const active=!expires||expires.getTime()>Date.now();const sub=product?subscriptions?.[product]:undefined;const willRenew=Boolean(sub?.auto_renewal_status==='will_renew');return{isPremium:active,expiresAt:entitlement.expires_date||null,productId:product,willRenew,status:active?'active':'expired',trialEndsAt:entitlement.period_type==='TRIAL'?entitlement.expires_date:null};}
export async function verifyPremiumStatus(appUserId:string):Promise<PremiumStatus>{if(!env.REVENUECAT_SECRET_KEY)throw new Error('RevenueCat server key tanımlı değil');const r=await axios.get(`https://api.revenuecat.com/v1/subscribers/${encodeURIComponent(appUserId)}`,{headers:{Authorization:`Bearer ${env.REVENUECAT_SECRET_KEY}`},timeout:8000});const sub=r.data?.subscriber||{};const entitlement=sub.entitlements?.[env.REVENUECAT_ENTITLEMENT_ID];return{appUserId,...subFor(entitlement,sub.subscriptions)};}
export function isValidWebhookAuth(authHeader:string|undefined){const expected=env.REVENUECAT_WEBHOOK_SECRET;if(!expected)return env.NODE_ENV!=='production';return authHeader===`Bearer ${expected}`;}
export async function syncRevenueCatToUser(userId:string,appUserId:string){const status=await verifyPremiumStatus(appUserId);await upsertSubscription(userId,{appUserId,entitlementId:env.REVENUECAT_ENTITLEMENT_ID,productId:status.productId,status:status.status,isPremium:status.isPremium,expiresAt:status.expiresAt,willRenew:status.willRenew,trialEndsAt:status.trialEndsAt});return status;}
export async function processWebhook(event:any){const appUserId=event?.app_user_id||event?.original_app_user_id;if(!appUserId)return null;const userId=await findUserIdByAppUserId(appUserId);if(!userId)return null;return syncRevenueCatToUser(userId,appUserId);}
async function findUserIdByAppUserId(appUserId:string){const u=await import('../db/database');if(!u.pool)return null;const r=await u.pool.query('SELECT user_id FROM subscriptions WHERE app_user_id=$1',[appUserId]);return r.rows[0]?.user_id||null;}
export async function bindRevenueCatUser(userId:string,appUserId:string){const user=await getUserById(userId);if(!user)throw new Error('Kullanıcı bulunamadı');if(appUserId!==userId)throw new Error('RevenueCat appUserId kullanıcı kimliğiyle eşleşmiyor');return syncRevenueCatToUser(userId,appUserId);}
